
development:
  adapter: postgresql
  database: blog
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: blog_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: blog_prod
  pool: 5
  timeout: 5000